version: "3.3"

services:
  kaddem:
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql_1:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      spring.jpa.hibernate.ddl-auto: update
    ports:
      - "8089:8089"
    depends_on:
      - docker-mysql_1

  docker-mysql_1:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Allow empty password
      MYSQL_DATABASE: kaddem
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql  # Persist data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
